name: Update GitHub Stats

on:
  schedule:
    - cron: '0 4 * * *'  # Runs at 04:00 UTC every day
  push:
    branches:
      - main  # Adjust if your default branch is different
  workflow_dispatch:

jobs:
  update-stats:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run fetch script
        run: node fetch-github-stats.js

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add general_stats.svg
          git commit -m "Update GitHub stats SVG"
          git push origin main
