name: Update GitHub Stats

on:
  schedule:
    - cron: '0 4 * * *'  # Runs at 04:00 UTC every day
  push:
    branches:
      - main  # Adjust if your default branch is different
  workflow_dispatch:
permissions:
  contents: write
  
jobs:
  update-stats:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Log Node.js version
        run: node -v

      - name: Install dependencies
        run: npm install

      - name: Run fetch script
        run: |
          node fetch-github-stats.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check SVG content
        run: cat general_stats.svg

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add general_stats.svg
          git commit -m "Update GitHub stats SVG"
          git push https://PAT@github.com/miarez/miarez.git HEAD:main
        env:
          PAT: ${{ secrets.PAT }}
